ece_article:
    resource: "@EceArticleBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: EceArticleBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout


articles:
    type: rest
    resource: @EceArticleBundle/Controller/ArticleApiController.php


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc