security:
    firewalls:
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~
            logout: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: ROLE_USER }

    providers:
#        default_provider:
#            memory:
#                users:
#                    rudy:  { password: 123456, roles: 'ROLE_USER' }
#                    benoit: { password: coucou, roles: 'ROLE_EDITEUR' }
        main:
            entity: { class: Ece\ArticleBundle\Entity\Auteur, property: email }

    encoders:
        Ece\ArticleBundle\Entity\Auteur: plaintext
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_EDITEUR:       ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
